version: '3.0'
services:
  web:
    build: .
    container_name: web-app    
    restart: "no"
    networks:
      - mahshev
networks:
  # Сеть должна быть предварительно создана командой: sudo docker network create -d bridge mahshev
  mahshev:
    external: true