version: '3.0'
services:
  web:
    build: .
    container_name: web-app    
    restart: "no"
    environment: 
      - VIRTUAL_HOST=dotnetapp01.apps.$VIRTUAL_HOST
      - LETSENCRYPT_HOST=dotnetapp01.apps.$LETSENCRYPT_HOST
    networks:
      - proxy_default
networks:
  proxy_default:
    external: true